CREATE DATABASE $(OPEN5ETOOLS_DB);
GO
USE $(OPEN5ETOOLS_DB);
GO
CREATE LOGIN $(OPEN5ETOOLS_USER) WITH PASSWORD = '$(OPEN5ETOOLS_PASSWORD)';
GO
CREATE USER $(OPEN5ETOOLS_USER) FOR LOGIN $(OPEN5ETOOLS_USER);
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [$(OPEN5ETOOLS_USER)];
GO